"""add_event_data_to_orders

Revision ID: 480825ef6e19
Revises: a595e29f71d9
Create Date: 2026-04-07 21:03:02.821300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480825ef6e19'
down_revision = 'a595e29f71d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('event_venue', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('event_venue')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
