"""Initial migration

Revision ID: a595e29f71d9
Revises: 
Create Date: 2026-02-20 18:39:02.075980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a595e29f71d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('allowed_events', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rate_limit_per_minute > 0 AND rate_limit_per_minute <= 1000', name='check_rate_limit_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_client_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_time', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('sale_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('resale_allowed', sa.Boolean(), nullable=False),
    sa.Column('resale_max_price_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_cents >= 0', name='check_price_positive'),
    sa.CheckConstraint('quantity_reserved >= 0', name='check_quantity_reserved_positive'),
    sa.CheckConstraint('quantity_sold >= 0 AND quantity_sold <= quantity_total', name='check_quantity_sold_valid'),
    sa.CheckConstraint('resale_max_price_percent >= 100 AND resale_max_price_percent <= 200', name='check_resale_percent_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_types_event_status', ['event_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_types_event_id'), ['event_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_client_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'refunded', 'expired')", name='check_order_status_valid'),
    sa.CheckConstraint('total_cents >= 0', name='check_total_positive'),
    sa.ForeignKeyConstraint(['api_client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_event', ['event_id'], unique=False)
        batch_op.create_index('idx_orders_expires', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
        batch_op.create_index('idx_orders_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.CheckConstraint('unit_price_cents >= 0', name='check_unit_price_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('original_owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_secret', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transferred_count', sa.Integer(), nullable=False),
    sa.Column('last_transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('valid', 'used', 'invalidated', 'listed', 'transferred')", name='check_ticket_status_valid'),
    sa.CheckConstraint('transferred_count >= 0', name='check_transferred_count_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_secret')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('idx_tickets_order', ['order_id'], unique=False)
        batch_op.create_index('idx_tickets_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_owner_id'), ['owner_id'], unique=False)

    op.create_table('resale_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=False),
    sa.Column('original_price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'sold', 'cancelled', 'expired')", name='check_listing_status_valid'),
    sa.CheckConstraint('asking_price_cents > 0', name='check_asking_price_positive'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('resale_listings', schema=None) as batch_op:
        batch_op.create_index('idx_resale_active_event', ['event_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
        batch_op.create_index(batch_op.f('ix_resale_listings_seller_id'), ['seller_id'], unique=False)

    op.create_table('validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('result_details', sa.String(length=200), nullable=True),
    sa.Column('scanned_by', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("result IN ('valid', 'already_used', 'invalid_signature', 'invalid_status', 'wrong_event', 'not_found')", name='check_validation_result_valid'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.create_index('idx_validations_event_time', ['event_id', 'scanned_at'], unique=False)
        batch_op.create_index('idx_validations_ticket', ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.drop_index('idx_validations_ticket')
        batch_op.drop_index('idx_validations_event_time')

    op.drop_table('validations')
    with op.batch_alter_table('resale_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resale_listings_seller_id'))
        batch_op.drop_index('idx_resale_active_event', postgresql_where=sa.text("status = 'active'"))

    op.drop_table('resale_listings')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_owner_id'))
        batch_op.drop_index('idx_tickets_owner_status')
        batch_op.drop_index('idx_tickets_order')

    op.drop_table('tickets')
    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index('idx_orders_user_status')
        batch_op.drop_index('idx_orders_expires', postgresql_where=sa.text("status = 'pending'"))
        batch_op.drop_index('idx_orders_event')

    op.drop_table('orders')
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_types_event_id'))
        batch_op.drop_index('idx_ticket_types_event_status')

    op.drop_table('ticket_types')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_time')
        batch_op.drop_index('idx_audit_entity')

    op.drop_table('audit_logs')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
