"""Initial migration

Revision ID: 670c423c27c6
Revises: 
Create Date: 2026-03-12 16:49:54.120045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '670c423c27c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('min_user_posts', sa.Integer(), nullable=True),
    sa.Column('thread_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('forum_categories', schema=None) as batch_op:
        batch_op.create_index('idx_forum_categories_order', ['order'], unique=False)
        batch_op.create_index('idx_forum_categories_slug', ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('soundcloud_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('mixcloud_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'artist', 'organizer', 'moderator', 'admin')", name='check_user_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=True)
        batch_op.create_index('idx_users_username', ['username'], unique=True)

    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index('idx_venues_city', ['city'], unique=False)
        batch_op.create_index('idx_venues_slug', ['slug'], unique=True)

    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('soundcloud_url', sa.String(length=255), nullable=True),
    sa.Column('mixcloud_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('bandcamp_url', sa.String(length=255), nullable=True),
    sa.Column('spotify_url', sa.String(length=255), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index('idx_artists_name', ['name'], unique=False)
        batch_op.create_index('idx_artists_slug', ['slug'], unique=True)

    op.create_table('forum_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('preview_content', sa.String(length=500), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_post_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], ),
    sa.ForeignKeyConstraint(['last_post_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.create_index('idx_forum_threads_author', ['author_id'], unique=False)
        batch_op.create_index('idx_forum_threads_category', ['category_id'], unique=False)
        batch_op.create_index('idx_forum_threads_pinned', ['is_pinned', 'last_post_at'], unique=False)

    op.create_table('organizers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.create_index('idx_organizers_slug', ['slug'], unique=True)
        batch_op.create_index('idx_organizers_user', ['user_id'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index('idx_playlists_creator', ['creator_id'], unique=False)
        batch_op.create_index('idx_playlists_public', ['is_public'], unique=False)

    op.create_table('user_follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id != following_id', name='check_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('event_reminders', sa.Boolean(), nullable=False),
    sa.Column('forum_replies', sa.Boolean(), nullable=False),
    sa.Column('new_followers', sa.Boolean(), nullable=False),
    sa.Column('privacy_profile', sa.String(length=20), nullable=False),
    sa.Column('show_listening_activity', sa.Boolean(), nullable=False),
    sa.Column('preferred_genres', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('preferred_cities', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("privacy_profile IN ('public', 'followers', 'private')", name='check_privacy_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doors_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('flyer_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('ticketing_enabled', sa.Boolean(), nullable=False),
    sa.Column('external_ticket_url', sa.String(length=500), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('interested_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'cancelled', 'completed')", name='check_event_status_valid'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_date', ['starts_at'], unique=False)
        batch_op.create_index('idx_events_organizer', ['organizer_id'], unique=False)
        batch_op.create_index('idx_events_slug', ['slug'], unique=True)
        batch_op.create_index('idx_events_status', ['status'], unique=False)

    op.create_table('forum_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_reason', sa.String(length=200), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('hidden_by', sa.UUID(), nullable=True),
    sa.Column('hidden_reason', sa.String(length=200), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hidden_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index('idx_forum_posts_author', ['author_id'], unique=False)
        batch_op.create_index('idx_forum_posts_thread', ['thread_id', 'created_at'], unique=False)

    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index('idx_albums_creator', ['creator_id'], unique=False)
        batch_op.create_index('idx_albums_event', ['event_id'], unique=False)

    op.create_table('archived_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_event_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer_name', sa.String(length=200), nullable=True),
    sa.Column('lineup_text', sa.Text(), nullable=True),
    sa.Column('flyer_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('recording_count', sa.Integer(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archived_events', schema=None) as batch_op:
        batch_op.create_index('idx_archived_events_city', ['city'], unique=False)
        batch_op.create_index('idx_archived_events_date', ['date'], unique=False)
        batch_op.create_index('idx_archived_events_year', ['year'], unique=False)
        batch_op.create_index(batch_op.f('ix_archived_events_year'), ['year'], unique=False)

    op.create_table('event_artists',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('set_time', sa.Time(), nullable=True),
    sa.Column('set_end_time', sa.Time(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('is_headliner', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'artist_id')
    )
    op.create_table('event_interests',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('forum_reactions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('like', 'fire', 'skull', 'heart', 'laugh')", name='check_reaction_type_valid'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('forum_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("reason IN ('spam', 'harassment', 'hate_speech', 'off_topic', 'other')", name='check_report_reason_valid'),
    sa.CheckConstraint("status IN ('pending', 'reviewed', 'actioned', 'dismissed')", name='check_report_status_valid'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.create_index('idx_forum_reports_status', ['status'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('waveform_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tracklist', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('audio_set', 'podcast', 'video', 'photo', 'flyer')", name='check_media_type_valid'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index('idx_media_created', ['created_at'], unique=False)
        batch_op.create_index('idx_media_event', ['event_id'], unique=False)
        batch_op.create_index('idx_media_type', ['type'], unique=False)
        batch_op.create_index('idx_media_uploader', ['uploader_id'], unique=False)

    op.create_table('archive_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('archived_event_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_contribution_status_valid'),
    sa.CheckConstraint("type IN ('event', 'recording', 'photo', 'flyer', 'info', 'correction')", name='check_contribution_type_valid'),
    sa.ForeignKeyConstraint(['archived_event_id'], ['archived_events.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive_contributions', schema=None) as batch_op:
        batch_op.create_index('idx_contributions_status', ['status'], unique=False)
        batch_op.create_index('idx_contributions_user', ['user_id'], unique=False)

    op.create_table('archive_flyers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived_event_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['archived_event_id'], ['archived_events.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive_flyers', schema=None) as batch_op:
        batch_op.create_index('idx_archive_flyers_event', ['archived_event_id'], unique=False)
        batch_op.create_index('idx_archive_flyers_year', ['year'], unique=False)

    op.create_table('media_likes',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'user_id')
    )
    op.create_table('playlist_items',
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'media_id')
    )
    op.create_table('set_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived_event_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('artist_name', sa.String(length=100), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tracklist', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("quality IN ('low', 'medium', 'high', 'lossless')", name='check_recording_quality_valid'),
    sa.CheckConstraint("source_type IN ('live_recording', 'soundboard', 'radio_rip', 'unknown')", name='check_source_type_valid'),
    sa.ForeignKeyConstraint(['archived_event_id'], ['archived_events.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set_recordings', schema=None) as batch_op:
        batch_op.create_index('idx_set_recordings_event', ['archived_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_recordings', schema=None) as batch_op:
        batch_op.drop_index('idx_set_recordings_event')

    op.drop_table('set_recordings')
    op.drop_table('playlist_items')
    op.drop_table('media_likes')
    with op.batch_alter_table('archive_flyers', schema=None) as batch_op:
        batch_op.drop_index('idx_archive_flyers_year')
        batch_op.drop_index('idx_archive_flyers_event')

    op.drop_table('archive_flyers')
    with op.batch_alter_table('archive_contributions', schema=None) as batch_op:
        batch_op.drop_index('idx_contributions_user')
        batch_op.drop_index('idx_contributions_status')

    op.drop_table('archive_contributions')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('idx_media_uploader')
        batch_op.drop_index('idx_media_type')
        batch_op.drop_index('idx_media_event')
        batch_op.drop_index('idx_media_created')

    op.drop_table('media_files')
    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_reports_status')

    op.drop_table('forum_reports')
    op.drop_table('forum_reactions')
    op.drop_table('event_interests')
    op.drop_table('event_artists')
    with op.batch_alter_table('archived_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archived_events_year'))
        batch_op.drop_index('idx_archived_events_year')
        batch_op.drop_index('idx_archived_events_date')
        batch_op.drop_index('idx_archived_events_city')

    op.drop_table('archived_events')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index('idx_albums_event')
        batch_op.drop_index('idx_albums_creator')

    op.drop_table('albums')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_posts_thread')
        batch_op.drop_index('idx_forum_posts_author')

    op.drop_table('forum_posts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_status')
        batch_op.drop_index('idx_events_slug')
        batch_op.drop_index('idx_events_organizer')
        batch_op.drop_index('idx_events_date')

    op.drop_table('events')
    op.drop_table('user_preferences')
    op.drop_table('user_follows')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index('idx_playlists_public')
        batch_op.drop_index('idx_playlists_creator')

    op.drop_table('playlists')
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.drop_index('idx_organizers_user')
        batch_op.drop_index('idx_organizers_slug')

    op.drop_table('organizers')
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_threads_pinned')
        batch_op.drop_index('idx_forum_threads_category')
        batch_op.drop_index('idx_forum_threads_author')

    op.drop_table('forum_threads')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index('idx_artists_slug')
        batch_op.drop_index('idx_artists_name')

    op.drop_table('artists')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index('idx_venues_slug')
        batch_op.drop_index('idx_venues_city')

    op.drop_table('venues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    with op.batch_alter_table('forum_categories', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_categories_slug')
        batch_op.drop_index('idx_forum_categories_order')

    op.drop_table('forum_categories')
    # ### end Alembic commands ###
